# This file was generated by GoReleaser. DO NOT EDIT.
cask "quiltfs" do
  version "0.18.1"

  on_macos do
    on_arm do
      sha256 "7d2004b6647abe84c77dbe1e831765b435406b80cccdc96308c6cc09438a0708"
      url "https://github.com/AskAlice/quiltfs/releases/download/v#{version}/quiltfs_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "811f7e994350d8639bc46f8d70cfdf8a0e53068b8f8abf9ecaefd9076c261319"
      url "https://github.com/AskAlice/quiltfs/releases/download/v#{version}/quiltfs_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "117f89c7ac8806c7115b9dc7951299592ba1df4653d7e826f0f51d748798e59b"
      url "https://github.com/AskAlice/quiltfs/releases/download/v#{version}/quiltfs_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ad63f4361ecb38f818e829afc26e9ab74863558c5eeedbbf418c7e7ece1be1c6"
      url "https://github.com/AskAlice/quiltfs/releases/download/v#{version}/quiltfs_#{version}_linux_amd64.tar.gz"
    end
  end

  name "quiltfs"
  desc "Encrypted filesystem spread across free storage services"
  homepage "https://github.com/AskAlice/quiltfs"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "quiltfs"

  # No zap stanza required

  caveats <<~EOS
    Mounting (quiltfs serve --mount) needs macFUSE: brew install --cask macfuse
  EOS
end
