# This file was generated by GoReleaser. DO NOT EDIT.
cask "quiltfs" do
  version "0.18.0"

  on_macos do
    on_arm do
      sha256 "e088450e93fff28bdaf9f6ef2cb406e8cd4e7c54e331074eb82b6689ce9e7462"
      url "https://github.com/AskAlice/quiltfs/releases/download/v#{version}/quiltfs_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "0b697a65d47bb480b4dcf8076e28b357d36fd11f4530a05282adf489d0940625"
      url "https://github.com/AskAlice/quiltfs/releases/download/v#{version}/quiltfs_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "372c632cd9114471f823c52730b399efdf597935d64fd9ed2711af21ea633124"
      url "https://github.com/AskAlice/quiltfs/releases/download/v#{version}/quiltfs_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "9208f93e066d8f33c96be906b3084661edcf5200ccaf74e2e952fcc0ed24281a"
      url "https://github.com/AskAlice/quiltfs/releases/download/v#{version}/quiltfs_#{version}_linux_amd64.tar.gz"
    end
  end

  name "quiltfs"
  desc "Encrypted filesystem spread across free storage services"
  homepage "https://github.com/AskAlice/quiltfs"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "quiltfs"

  # No zap stanza required

  caveats <<~EOS
    Mounting (quiltfs serve --mount) needs macFUSE: brew install --cask macfuse
  EOS
end
