# This file was generated by GoReleaser. DO NOT EDIT.
cask "quiltfs" do
  version "0.18.2"

  on_macos do
    on_arm do
      sha256 "21e6d94c790b162025335ef98e563cf17b5c085c3f2f24a6c7f1562b58e948e8"
      url "https://github.com/AskAlice/quiltfs/releases/download/v#{version}/quiltfs_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "4a26be4177112f6b738c99f6d9c3cce5fe3563a0fa9bea65ec4f8b3a4f779a7a"
      url "https://github.com/AskAlice/quiltfs/releases/download/v#{version}/quiltfs_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "efa2ae88781c2b50351ae57701a7e68247c52ebf5fe0e844acfe12d2429aff61"
      url "https://github.com/AskAlice/quiltfs/releases/download/v#{version}/quiltfs_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "9e1e239731b3df34774e66eb86a4f6ee17388db9c4a6004fbb33a0b1dc925055"
      url "https://github.com/AskAlice/quiltfs/releases/download/v#{version}/quiltfs_#{version}_linux_amd64.tar.gz"
    end
  end

  name "quiltfs"
  desc "Encrypted filesystem spread across free storage services"
  homepage "https://github.com/AskAlice/quiltfs"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "quiltfs"

  # No zap stanza required

  caveats <<~EOS
    Mounting (quiltfs serve --mount) needs macFUSE: brew install --cask macfuse
  EOS
end
